server:
  port: 8081
  servlet.context-path: /

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    com:
      weison:
        sbmp:
          mapper: DEBUG

spring:
  data:
  datasource:
    # 遇到时区问题用这个
    # jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1
    # schema.sql中一般存放的是DDL脚本，即通常为创建或更新库表的脚本
    # data.sql中一般是DML脚本，即通常为数据插入脚本
    #schema: classpath:schema.sql
    #data: classpath:data.sql
    platform: mysql
    initialization-mode: always
    continue-on-error: false
    #data-password:
    #data-username:
    #schema-password:
    #schema-username:
    sql-script-encoding: utf-8
    separator: ;
    # type: com.alibaba.druid.pool.DruidDataSource
